name: runanalyze_mobile
description: Minimal Flutter app to show weekly/monthly/annual activity stats
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^1.2.0
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
